import { createSlice } from "@reduxjs/toolkit";
import { images } from "../../../utils/images";

const inspectionsList = [
  {
    id: 1,
    customerNit: 901000002,
    elevatorId: 1,
    quotation: 7001,
    uniqueConsecutive: "A7001",
    evaluations: [
      {
        id: 1,
        item: 1,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 37,
        item: 37,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 38,
        item: 38,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 39,
        item: 39,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: false,
        images: [images[1].image, images[0].image, images[2].image],
      },
      {
        id: 40,
        item: 40,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 41,
        item: 41,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 42,
        item: 42,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 43,
        item: 43,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [],
      },
      {
        id: 44,
        item: 44,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 45,
        item: 45,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [],
      },
      {
        id: 46,
        item: 46,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 47,
        item: 47,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 48,
        item: 48,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 49,
        item: 49,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 50,
        item: 50,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 51,
        item: 51,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 52,
        item: 52,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 53,
        item: 53,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 2,
    customerNit: 901000004,
    elevatorId: 2,
    quotation: 7002,
    uniqueConsecutive: "A7002",
    evaluations: [
      {
        id: 4,
        item: 4,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 5,
        item: 5,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 6,
        item: 6,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 3,
    customerNit: 901000004,
    elevatorId: 3,
    quotation: 7003,
    uniqueConsecutive: "A7003",
    evaluations: [
      {
        id: 7,
        item: 7,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 8,
        item: 8,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 9,
        item: 9,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 4,
    customerNit: 901000006,
    elevatorId: 4,
    quotation: 7004,
    uniqueConsecutive: "A7004",
    evaluations: [
      {
        id: 10,
        item: 10,
        status: false,
        observation:
          "ACCESO AL CUARTO DE MAQUINAS NO CUMPLE CON MEDIDAS DE SEGURIDAD",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 11,
        item: 11,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 12,
        item: 12,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 5,
    customerNit: 901000007,
    elevatorId: 5,
    quotation: 7005,
    uniqueConsecutive: "A7005",
    evaluations: [
      {
        id: 13,
        item: 13,
        status: false,
        observation: "",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 14,
        item: 14,
        status: false,
        observation: "",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 15,
        item: 15,
        status: false,
        observation: "",
        corrected: false,
        images: [images[0].image, images[1].image, images[2].image],
      },
    ],
  },
  {
    id: 6,
    customerNit: 901000009,
    elevatorId: 6,
    quotation: 7006,
    uniqueConsecutive: "A7006",
    evaluations: [
      {
        id: 16,
        item: 16,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 17,
        item: 17,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 18,
        item: 18,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 7,
    customerNit: 901000010,
    elevatorId: 7,
    quotation: 7007,
    uniqueConsecutive: "A7007",
    evaluations: [
      {
        id: 19,
        item: 19,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 20,
        item: 20,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 21,
        item: 21,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 8,
    customerNit: 901000011,
    elevatorId: 8,
    quotation: 7008,
    uniqueConsecutive: "A7008",
    evaluations: [
      {
        id: 22,
        item: 21,
        status: true,
        observation: "",
        corrected: true,
        images: [],
      },
      {
        id: 23,
        item: 22,
        status: false,
        observation: "",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
      {
        id: 24,
        item: 23,
        status: false,
        observation: "",
        corrected: true,
        images: [images[0].image, images[1].image, images[2].image],
      },
    ],
  },
  {
    id: 9,
    customerNit: 901000012,
    elevatorId: 9,
    quotation: 7009,
    uniqueConsecutive: "A7009",
    evaluations: [
      {
        id: 25,
        item: 11,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 26,
        item: 12,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 27,
        item: 13,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 10,
    customerNit: 901000013,
    elevatorId: 10,
    quotation: 7010,
    uniqueConsecutive: "A7010",
    evaluations: [
      {
        id: 28,
        item: 11,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 29,
        item: 20,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 30,
        item: 30,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 11,
    customerNit: 901000014,
    elevatorId: 11,
    quotation: 7011,
    uniqueConsecutive: "A7011",
    evaluations: [
      {
        id: 31,
        item: 1,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 32,
        item: 2,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 33,
        item: 30,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 12,
    customerNit: 901000015,
    elevatorId: 12,
    quotation: 7012,
    uniqueConsecutive: "A7012",
    evaluations: [
      {
        id: 34,
        item: 1,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 35,
        item: 23,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 36,
        item: 31,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 13,
    customerNit: 901000016,
    elevatorId: 13,
    quotation: 7013,
    uniqueConsecutive: "A7013",
    evaluations: [
      {
        id: 37,
        item: 16,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 38,
        item: 2,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 39,
        item: 30,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 14,
    customerNit: 901000017,
    elevatorId: 14,
    quotation: 7014,
    uniqueConsecutive: "A7014",
    evaluations: [
      {
        id: 40,
        item: 15,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 41,
        item: 28,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 42,
        item: 3,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 15,
    customerNit: 901000018,
    elevatorId: 15,
    quotation: 7015,
    uniqueConsecutive: "A7015",
    evaluations: [
      {
        id: 43,
        item: 1,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 44,
        item: 29,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 45,
        item: 23,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 16,
    customerNit: 901000019,
    elevatorId: 16,
    quotation: 7016,
    uniqueConsecutive: "A7016",
    evaluations: [
      {
        id: 46,
        item: 19,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 47,
        item: 2,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 48,
        item: 36,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 18,
    customerNit: 901000001,
    elevatorId: 18,
    quotation: 7017,
    uniqueConsecutive: "A7017",
    evaluations: [
      {
        id: 49,
        item: 11,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 50,
        item: 22,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 51,
        item: 33,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 19,
    customerNit: 901000002,
    elevatorId: 19,
    quotation: 7018,
    uniqueConsecutive: "A7018",
    evaluations: [
      {
        id: 52,
        item: 1,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 53,
        item: 2,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 54,
        item: 35,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 20,
    customerNit: 901000003,
    elevatorId: 20,
    quotation: 7019,
    uniqueConsecutive: "A7019",
    evaluations: [
      {
        id: 55,
        item: 1,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 56,
        item: 28,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 57,
        item: 3,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 21,
    customerNit: 901000003,
    elevatorId: 21,
    quotation: 7020,
    uniqueConsecutive: "A7020",
    evaluations: [
      {
        id: 58,
        item: 1,
        status: false,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 59,
        item: 2,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
      {
        id: 60,
        item: 31,
        status: true,
        observation: "",
        corrected: true,
        images: [images[1].image],
      },
    ],
  },
  {
    id: 22,
    customerNit: 901000004,
    elevatorId: 22,
    quotation: 7021,
    uniqueConsecutive: "A7021",
    evaluations: [
      {
        id: 61,
        item: 17,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 62,
        item: 2,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
      {
        id: 63,
        item: 3,
        status: false,
        observation: "",
        corrected: false,
        images: [images[1].image],
      },
    ],
  },
];

export const InspectionSlice = createSlice({
  name: "inspections",
  initialState: {
    inspections: inspectionsList,
  },

  reducers: {
    setInspections: (state, action) => {
      state.inspections = action.payload;
    },
  },
});

export const { setInspections } = InspectionSlice.actions;
