import { createSlice } from "@reduxjs/toolkit";

const elevatorsList = [
  {
    "id": 1,
    "customerNit": 901000002,
    "elevatorId": "ASC 1",
    "brand": "Otis",
    "stopsNumber": 10,
    "driveType": "Hydraulic",
    "controlType": "Automatic",
    "serialNumber": "SN123456",
    "manufacturer": "Otis Manufacturing",
    "maintenanceCompany": "LiftCare Ltd",
    "technicianName": "Carlos Perez",
    "lastMaintenanceDate": "2024-05-12",
    "commissioningDate": "2020-01-10",
    "lastInspectionDate": "2024-07-20",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 800,
    "capacityPersons": 10,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1500,
    "bufferType": "Hydraulic"
  },
  {
    "id": 2,
    "customerNit": 901000004,
    "elevatorId": "ASC IMPAR",
    "brand": "Schindler",
    "stopsNumber": 12,
    "driveType": "Electric",
    "controlType": "Manual",
    "serialNumber": "SN654321",
    "manufacturer": "Schindler Group",
    "maintenanceCompany": "ElevatorFix SA",
    "technicianName": "Maria Gomez",
    "lastMaintenanceDate": "2024-03-18",
    "commissioningDate": "2019-11-05",
    "lastInspectionDate": "2024-06-10",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 1000,
    "capacityPersons": 12,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1800,
    "bufferType": "Spring"
  },
  {
    "id": 3,
    "customerNit": 901000004,
    "elevatorId": "ASC PAR",
    "brand": "Kone",
    "stopsNumber": 8,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN987654",
    "manufacturer": "Kone Oyj",
    "maintenanceCompany": "VerticalMove SAS",
    "technicianName": "Luis Herrera",
    "lastMaintenanceDate": "2024-04-22",
    "commissioningDate": "2021-02-15",
    "lastInspectionDate": "2024-08-01",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 600,
    "capacityPersons": 8,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1400,
    "bufferType": "Hydraulic"
  },
  {
    "id": 4,
    "customerNit": 901000006,
    "elevatorId": "ASC 1",
    "brand": "ThyssenKrupp",
    "stopsNumber": 15,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN456789",
    "manufacturer": "ThyssenKrupp AG",
    "maintenanceCompany": "LiftExperts LTDA",
    "technicianName": "Andres Silva",
    "lastMaintenanceDate": "2024-02-11",
    "commissioningDate": "2018-09-22",
    "lastInspectionDate": "2024-05-19",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 1200,
    "capacityPersons": 15,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 2000,
    "bufferType": "Spring"
  },
  {
    "id": 5,
    "customerNit": 901000007,
    "elevatorId": "ASC 2",
    "brand": "Mitsubishi",
    "stopsNumber": 9,
    "driveType": "Hydraulic",
    "controlType": "Manual",
    "serialNumber": "SN111222",
    "manufacturer": "Mitsubishi Electric",
    "maintenanceCompany": "AscensorTech",
    "technicianName": "Diana Lopez",
    "lastMaintenanceDate": "2024-06-05",
    "commissioningDate": "2022-03-17",
    "lastInspectionDate": "2024-07-28",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 700,
    "capacityPersons": 9,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1600,
    "bufferType": "Hydraulic"
  },
  {
    "id": 6,
    "customerNit": 901000009,
    "elevatorId": "ASC IMPAR",
    "brand": "Hyundai",
    "stopsNumber": 14,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN333444",
    "manufacturer": "Hyundai Elevators",
    "maintenanceCompany": "GlobalLift",
    "technicianName": "Pedro Martinez",
    "lastMaintenanceDate": "2024-05-10",
    "commissioningDate": "2020-06-30",
    "lastInspectionDate": "2024-07-15",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 1100,
    "capacityPersons": 14,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1750,
    "bufferType": "Spring"
  },
  {
    "id": 7,
    "customerNit": 901000010,
    "elevatorId": "ASC PAR",
    "brand": "Hitachi",
    "stopsNumber": 11,
    "driveType": "Hydraulic",
    "controlType": "Manual",
    "serialNumber": "SN555666",
    "manufacturer": "Hitachi Elevators",
    "maintenanceCompany": "LiftSolutions",
    "technicianName": "Sofia Torres",
    "lastMaintenanceDate": "2024-03-29",
    "commissioningDate": "2021-01-25",
    "lastInspectionDate": "2024-06-18",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 900,
    "capacityPersons": 11,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1550,
    "bufferType": "Hydraulic"
  },
  {
    "id": 8,
    "customerNit": 901000011,
    "elevatorId": "ASC 2",
    "brand": "Sigma",
    "stopsNumber": 7,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN777888",
    "manufacturer": "Sigma Co",
    "maintenanceCompany": "AndesLift",
    "technicianName": "Juan Alvarez",
    "lastMaintenanceDate": "2024-02-07",
    "commissioningDate": "2019-04-12",
    "lastInspectionDate": "2024-07-03",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 650,
    "capacityPersons": 7,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1300,
    "bufferType": "Spring"
  },
  {
    "id": 9,
    "customerNit": 901000012,
    "elevatorId": "ASC IMPAR",
    "brand": "Fujitec",
    "stopsNumber": 13,
    "driveType": "Hydraulic",
    "controlType": "Automatic",
    "serialNumber": "SN999000",
    "manufacturer": "Fujitec Co",
    "maintenanceCompany": "LiftAndGo",
    "technicianName": "Angela Ruiz",
    "lastMaintenanceDate": "2024-04-10",
    "commissioningDate": "2020-08-22",
    "lastInspectionDate": "2024-07-30",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 950,
    "capacityPersons": 13,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1650,
    "bufferType": "Hydraulic"
  },
  {
    "id": 10,
    "customerNit": 901000013,
    "elevatorId": "ASC PAR",
    "brand": "LG",
    "stopsNumber": 6,
    "driveType": "Electric",
    "controlType": "Manual",
    "serialNumber": "SN112233",
    "manufacturer": "LG Corp",
    "maintenanceCompany": "LiftExpress",
    "technicianName": "Ricardo Sanchez",
    "lastMaintenanceDate": "2024-06-12",
    "commissioningDate": "2022-07-08",
    "lastInspectionDate": "2024-08-05",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 500,
    "capacityPersons": 6,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1200,
    "bufferType": "Spring"
  },
  {
    "id": 11,
    "customerNit": 901000014,
    "elevatorId": "ASC 1",
    "brand": "Toshiba",
    "stopsNumber": 16,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN445566",
    "manufacturer": "Toshiba Corp",
    "maintenanceCompany": "ElevatePro",
    "technicianName": "Gabriela Romero",
    "lastMaintenanceDate": "2024-01-20",
    "commissioningDate": "2018-05-19",
    "lastInspectionDate": "2024-06-22",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 1300,
    "capacityPersons": 16,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 2100,
    "bufferType": "Hydraulic"
  },
  {
    "id": 12,
    "customerNit": 901000015,
    "elevatorId": "ASC 2",
    "brand": "ExpressLift",
    "stopsNumber": 5,
    "driveType": "Hydraulic",
    "controlType": "Manual",
    "serialNumber": "SN778899",
    "manufacturer": "ExpressLift Ltd",
    "maintenanceCompany": "QuickLift",
    "technicianName": "Hector Vasquez",
    "lastMaintenanceDate": "2024-07-09",
    "commissioningDate": "2023-01-05",
    "lastInspectionDate": "2024-08-12",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 400,
    "capacityPersons": 5,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1100,
    "bufferType": "Spring"
  },
  {
    "id": 13,
    "customerNit": 901000016,
    "elevatorId": "ASC IMPAR",
    "brand": "Omega",
    "stopsNumber": 20,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN889900",
    "manufacturer": "Omega Corp",
    "maintenanceCompany": "PrimeLift",
    "technicianName": "Isabel Moreno",
    "lastMaintenanceDate": "2024-03-03",
    "commissioningDate": "2017-09-18",
    "lastInspectionDate": "2024-07-25",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 1500,
    "capacityPersons": 20,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 2300,
    "bufferType": "Hydraulic"
  },
  {
    "id": 14,
    "customerNit": 901000017,
    "elevatorId": "ASC PAR",
    "brand": "SilverLift",
    "stopsNumber": 18,
    "driveType": "Hydraulic",
    "controlType": "Automatic",
    "serialNumber": "SN667788",
    "manufacturer": "SilverLift SA",
    "maintenanceCompany": "LiftPro",
    "technicianName": "Valentina Castro",
    "lastMaintenanceDate": "2024-02-14",
    "commissioningDate": "2016-11-22",
    "lastInspectionDate": "2024-07-16",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 1400,
    "capacityPersons": 18,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1900,
    "bufferType": "Spring"
  },
  {
    "id": 15,
    "customerNit": 901000018,
    "elevatorId": "ASC 1",
    "brand": "GoldenLift",
    "stopsNumber": 22,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN998877",
    "manufacturer": "GoldenLift Inc",
    "maintenanceCompany": "EliteElevators",
    "technicianName": "Fernando Rios",
    "lastMaintenanceDate": "2024-01-25",
    "commissioningDate": "2015-12-10",
    "lastInspectionDate": "2024-06-28",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 1600,
    "capacityPersons": 22,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 2400,
    "bufferType": "Hydraulic"
  },
  {
    "id": 16,
    "customerNit": 901000019,
    "elevatorId": "ASC 2",
    "brand": "MaxLift",
    "stopsNumber": 4,
    "driveType": "Hydraulic",
    "controlType": "Manual",
    "serialNumber": "SN334455",
    "manufacturer": "MaxLift Ltd",
    "maintenanceCompany": "GoUpFast",
    "technicianName": "Carolina Duarte",
    "lastMaintenanceDate": "2024-05-08",
    "commissioningDate": "2023-02-28",
    "lastInspectionDate": "2024-07-19",
    "machineType": "Hydraulic",
    "threading": "Belt",
    "capacityKg": 300,
    "capacityPersons": 4,
    "governor": "No",
    "tractionBy": "Motor",
    "machineRoom": "No",
    "pitDepthMm": 1000,
    "bufferType": "Spring"
  },
  {
    "id": 17,
    "customerNit": 901000020,
    "elevatorId": "ASC IMPAR",
    "brand": "AlphaLift",
    "stopsNumber": 17,
    "driveType": "Electric",
    "controlType": "Automatic",
    "serialNumber": "SN223344",
    "manufacturer": "AlphaLift Corp",
    "maintenanceCompany": "LiftMasters",
    "technicianName": "Sebastian Vega",
    "lastMaintenanceDate": "2024-06-20",
    "commissioningDate": "2019-03-11",
    "lastInspectionDate": "2024-08-02",
    "machineType": "Traction",
    "threading": "Rope",
    "capacityKg": 1350,
    "capacityPersons": 17,
    "governor": "Yes",
    "tractionBy": "Motor",
    "machineRoom": "Yes",
    "pitDepthMm": 1850,
    "bufferType": "Hydraulic"
  },
  {
    "id": "18",
    "customerNit": "901000001",
    "elevatorId": "ASC_IMPAR",
    "brand": "Mitsubishi",
    "stopsNumber": 10,
    "driveType": "Electromechanical",
    "controlType": "Automatic",
    "serialNumber": "SN-10001",
    "manufacturer": "Mitsubishi Electric",
    "maintenanceCompany": "ElevatorTech S.A.S",
    "technicianName": "Carlos López",
    "lastMaintenanceDate": "2024-01-15",
    "commissioningDate": "2018-07-20",
    "lastInspectionDate": "2024-05-01",
    "machineType": "Gearless",
    "threading": "Yes",
    "capacityKg": 800,
    "capacityPersons": 10,
    "governor": "Standard",
    "tractionBy": "Steel Cable",
    "machineRoom": "Yes",
    "pitDepthMm": 1500,
    "bufferType": "Hydraulic"
  },
  {
    "id": "19",
    "customerNit": "901000002",
    "elevatorId": "ASC_PAR",
    "brand": "Otis",
    "stopsNumber": 8,
    "driveType": "Hydraulic",
    "controlType": "Manual",
    "serialNumber": "SN-10002",
    "manufacturer": "Otis Worldwide",
    "maintenanceCompany": "LiftCare Ltda",
    "technicianName": "Andrés Ramírez",
    "lastMaintenanceDate": "2024-02-10",
    "commissioningDate": "2019-09-18",
    "lastInspectionDate": "2024-06-05",
    "machineType": "Geared",
    "threading": "No",
    "capacityKg": 600,
    "capacityPersons": 8,
    "governor": "Electronic",
    "tractionBy": "Chain",
    "machineRoom": "No",
    "pitDepthMm": 1300,
    "bufferType": "Spring"
  },
  {
    "id": "20",
    "customerNit": "901000003",
    "elevatorId": "ASC_01",
    "brand": "Schindler",
    "stopsNumber": 12,
    "driveType": "Electromechanical",
    "controlType": "Automatic",
    "serialNumber": "SN-10003",
    "manufacturer": "Schindler Group",
    "maintenanceCompany": "GlobalElevators",
    "technicianName": "María Torres",
    "lastMaintenanceDate": "2024-03-12",
    "commissioningDate": "2020-03-25",
    "lastInspectionDate": "2024-06-12",
    "machineType": "Gearless",
    "threading": "Yes",
    "capacityKg": 1000,
    "capacityPersons": 12,
    "governor": "Standard",
    "tractionBy": "Steel Cable",
    "machineRoom": "Yes",
    "pitDepthMm": 1600,
    "bufferType": "Hydraulic"
  },
  {
    "id": "21",
    "customerNit": "901000003",
    "elevatorId": "ASC_02",
    "brand": "Kone",
    "stopsNumber": 6,
    "driveType": "Hydraulic",
    "controlType": "Automatic",
    "serialNumber": "SN-10004",
    "manufacturer": "Kone Corporation",
    "maintenanceCompany": "ElevatorPro",
    "technicianName": "Luis Martínez",
    "lastMaintenanceDate": "2024-04-08",
    "commissioningDate": "2021-11-15",
    "lastInspectionDate": "2024-07-01",
    "machineType": "Geared",
    "threading": "No",
    "capacityKg": 500,
    "capacityPersons": 6,
    "governor": "Electronic",
    "tractionBy": "Hydraulic Pump",
    "machineRoom": "No",
    "pitDepthMm": 1200,
    "bufferType": "Spring"
  },
  {
    "id": "22",
    "customerNit": "901000004",
    "elevatorId": "ASC_03",
    "brand": "ThyssenKrupp",
    "stopsNumber": 15,
    "driveType": "Electromechanical",
    "controlType": "Automatic",
    "serialNumber": "SN-10005",
    "manufacturer": "TK Elevator",
    "maintenanceCompany": "Subir S.A.",
    "technicianName": "Jorge Pérez",
    "lastMaintenanceDate": "2024-05-03",
    "commissioningDate": "2017-05-21",
    "lastInspectionDate": "2024-08-01",
    "machineType": "Gearless",
    "threading": "Yes",
    "capacityKg": 1200,
    "capacityPersons": 15,
    "governor": "Standard",
    "tractionBy": "Steel Cable",
    "machineRoom": "Yes",
    "pitDepthMm": 1800,
    "bufferType": "Hydraulic"
  }
]




export const ElevatorSlice = createSlice({
  name: "elevators",
  initialState: {
    elevators: elevatorsList,
  },

  reducers: {
    setElevator: (state, action) => {
      state.elevators = action.payload;
    },
  },
});

export const {
  setElevator
} = ElevatorSlice.actions;

